# -*- coding: utf-8 -*-
"""CV-LAB-04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ul9zaGsisl34bZ__N10CzmByACnN4f94

Read an image in python  and  Dilate an Image using Dilate function.
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img = cv2.imread('Picture4.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.ones((5,5), np.uint8)
dilated_img = cv2.dilate(img, kernel, iterations=1)
cv2.imwrite('Dilated_Image.jpg', dilated_img)
cv2_imshow(dilated_img)