# -*- coding: utf-8 -*-
"""CV-LAB-05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jfQQmZw-31NmmbWek-c6UGvLHQp8cVJ
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img = cv2.imread("Picture5.jpg")
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
eroded_image = cv2.erode(gray_image, kernel, iterations=1)
cv2.imwrite("eroded_image.jpg",eroded_image)
cv2_imshow(eroded_image)