# -*- coding: utf-8 -*-
"""CV-LAB-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtpZ3Nll_KD8NnwElMhNxOxrZsJSW5XZ
"""

import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread('Picture2.jpg')
blur = cv2.GaussianBlur(image, (5, 5), 10)
cv2.imwrite('blurred_image.jpg', blur)
cv2_imshow(blur)