# -*- coding: utf-8 -*-
"""CV-LAB-03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXbNiJEzt55fGW4cyr9qXKMKXskB0TwL
"""

import cv2
from google.colab import files
import numpy as np
from google.colab.patches import cv2_imshow

uploaded = files.upload()

filename = next(iter(uploaded))
image_bytes = uploaded[filename]

np_array = np.frombuffer(image_bytes, np.uint8)

img = cv2.imdecode(np_array, cv2.IMREAD_COLOR)

if img is None:
    raise ValueError(f"Error: Could not load image '{filename}'. It might be an unsupported format or corrupted.")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 100, 200)
cv2.imwrite('Canny_Edges_3rd.jpg', edges)
cv2_imshow(edges)